Exit the loop when we don't have a package
When the system doesn't know about a package, then we know we need it.
Attempting to check for version match leads to an error:

  TypeError: object of type 'NoneType' has no len()

Go ahead and bail out once we know we don't have the package.

Also added a test which triggers the error without the continue.

Story: 2000955
Change-Id: Ib044b5de62aa09274054c3ff1d8e4cb860ba9a11